### ISSUE TITLE
Button 'Evaluation auswerten' auf result.html entfernen

### ISSUE THREAD

**Issue by MarEliSeg** [DomixD/MFEM#10]
Aufwand: 0,5 PT
Die Berechnung soll schon bei dem vorherigen Buttonklick (auf checkQuest.html 'Evaluation auswerten') geschehen, gleichzeitig werden aber die Daten erst in die Datenbank geschrieben. 

______________________________________________________________________________

DoD:
- [x] testen (curl und GUI)
- [x] review (code und testen)

**Comment by ThoGro** [comment]
getResult() in evaluation() aufrufen und resultEva als $rootScope speichern.

**Comment by ThoGro** [comment]
Dauer: 1 Stunde
