### ISSUE TITLE
Rechte-Rollen-Konzept implementieren

### ISSUE THREAD

**Issue by MarEliSeg** [DomixD/MFEM#31]
Zugriff soll rechtebasierend erfolgen
- [x] für jeden Befehl Rechte anlegen
- [x] Datenbankschema anpassen
- [x] Rechte den Rollen zuweisen
- [x] In den Repos per Annotations die Rechte zuweisen
- [x] bei Zugriff prüfen, ob die Rolle die nötigen Rechte hat

______________________________________________________________________________

DoD:
- [x] testen (curl und GUI)
- [x] review (code und testen)

**Comment by MarEliSeg** [comment]
|Verschiedene Rechte:                               |Verschiedene Rollen:|
|-----------------------------------------------------|---------------------------|
|1) create Classification                              |Creator|
|2) create Requirement                              |Creator|
|3) create Question                                    |Creator|
|4) create Metric                                        |Creator|
|5) Evaluation                                            |Evaluator|
|5.1) create Framework                               |Evaluator|
|5.2) create FW Evaluation                           |Evaluator|
|5.3) create Evaluation Result                      |Evaluator|
|6) read Access (alle außer 'read User')    |Creator & Evaluator|
|7) Admin access                                      |Admin|
|7.1) read User                                             |Admin|
|7.2) create User|Admin|
|8) Category (create sperren)

**Comment by MrSebastian** [comment]
im Wiki ist noch Platz für diese Tabelle damit man nicht immer nach dem Issue suchen muss

**Comment by MrSebastian** [comment]
bitte schaut euch mit an wie leicht bei euch Rechte ergänzt werden können. Was muss erfolgen wenn ihr ein neues Recht einführt. Ein User kann auch mehrere Rollen haben.

**Comment by MrSebastian** [comment]
im besten Fall braucht ihr am Ende nur noch `@PreAuthorize("hasAuthority('dasNotwendigeRecht')")`. In eurer Implementierung von `UserDetailsService` geht ihr nur auf die Rechte ein.

**Comment by ThoGro** [comment]
Ein User kann jetzt mehrere Rollen haben.

**Comment by ThoGro** [comment]
Die Ansicht der App ist nicht auf die verschiedenen Rollen angepasst.
