### ISSUE TITLE
Testschulden beheben

### ISSUE THREAD

**Issue by MarEliSeg** [DomixD/MFEM#5]
Tests für
- [x] Ressource
- [x] Service
- [x] Repo (selbstdefinierte DB-Anfragen)

______________________________________________________________________________

DoD:
- [x] review (code und testen)

**Comment by DomixD** [comment]
Probleme beim testen von ServiceImplTest.

**Comment by ThoGro** [comment]
findByClassification aus RepoFrameworkEvaluation testen #8

**Comment by ThoGro** [comment]
Alternative für @AllArgsConstructor and @NoArgsConstructor suchen

**Comment by ThoGro** [comment]
Das Schreiben der Testfälle geschaltet sich aufwendiger als geplant und wird daher mit in den 3. Sprint übernommen.

**Comment by xdoo** [comment]
Hier wie am Montag besprochen der Link zu meinem Repo:
https://github.com/xdoo/oauth2_password_flow_sample/tree/master/resource_server_001/src/test/java/com/example

**Comment by MarEliSeg** [comment]
Issue wird in den nächsten Milestone (4. Sprint) übernommen.
- Controller (Resource): läuft soweit, Überlegung, ob MFEMService weggemockt wird
- Repos: passt!
- Service: passt!
- Integrationstests: fehlt bisher komplett
