### ISSUE TITLE
Funktionalität verschiedener Buttons anpassen

### ISSUE THREAD

**Issue by MarEliSeg** [DomixD/MFEM#6]
Aufwand: vermutlicht 0,5 PT
Herausfinden, warum bei diesen Buttons nicht in die Datenbank gespeichert wird.

1. Button: classiQuest 'weitere Frage'
2. Button: classiQuest 'weitere Anforderung'
3. Button: questReq 'weitere Frage'

**Comment by DomixD** [comment]
1. Button von classiQuest auf classiQuest
2. Button von classiQuest auf classiReq
3. eventuell löschen da duplicat

**Comment by ThoGro** [comment]
Probier die Funktionalität von onclick in die app.js zu verlagern, damit alles durch den Funktionsaufruf mit ng-click funktioniert.

**Comment by ThoGro** [comment]
Bitte die Inputfelder leeren!

**Comment by DomixD** [comment]
Danke für den Hinweis wurde geändert.
