### ISSUE TITLE
Antwortmöglichkeiten bei Metriken anpassen

### ISSUE THREAD

**Issue by MarEliSeg** [DomixD/MFEM#7]
Aufwand: 2 PT
flexible Anzahl an Antwortmöglichkeiten mit Berechnung der Gewichtung

- [x] Anpassen metric.html (hinzufügen und anordnen von Antworten)
- [x] Funktion für Gewichtung

______________________________________________________________________________

DoD:
- [x] testen (curl und GUI)
- [x] review (code und testen)

**Comment by ThoGro** [comment]
http://www.shanidkv.com/blog/angularjs-adding-form-fields-dynamically

**Comment by MarEliSeg** [comment]
Dauer: 1,5PT
