### ISSUE TITLE
Diagramm erstellen

### ISSUE THREAD

**Issue by MarEliSeg** [DomixD/MFEM#9]
Aufwand: 1PT
Netzdiagramm anhand des Ergebnisses der einzelnen Kategorien erstellen.

- [x] Diagramm erstellen
- [x] in html einfügen

______________________________________________________________________________

DoD:
- [x] testen (curl und GUI)
- [x] review (code und testen)

**Comment by ThoGro** [comment]
Dauer: 1,5 PT, da die Werte für das Diagramm erst mit dem falschen Typen vorlagen.
